<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOvcx7eB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOvcx7eB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOvcx7eB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOvcx7eB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOvcx7eB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ovcx7eB',
    'container.build_id' => 'a729f6b5',
    'container.build_time' => 1618462310,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOvcx7eB');
