<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqp05MS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqp05MS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSqp05MS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSqp05MS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSqp05MS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Sqp05MS',
    'container.build_id' => '542e429b',
    'container.build_time' => 1619655691,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqp05MS');
